[target.aarch64-unknown-linux-gnu]
dockerfile = "dockerfiles/Dockerfile.cross"
pre-build = [
    "apt-get update && apt-get install --assume-yes build-essential npm curl protobuf-compiler",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "mkdir -p /.npm",
    "chown -R 1000:1000 /.npm"
]

[target.x86_64-unknown-linux-gnu]
dockerfile = "dockerfiles/Dockerfile.builder"
pre-build = [
    "mkdir -p /.npm",
    "chown -R 1000:1000 /.npm"
]
