version: "3"
networks:
  server:
services:
  indexify:
    image: tensorlake/indexify-server
    ports:
      - 8900:8900
    networks:
      server:
        aliases:
          - indexify-server
    volumes:
      - data:/tmp/indexify-blob-storage
  ultralytics-image:
    # Use this for GPU support
    # image: tensorlake/pdf-blueprint-pdf-parser-gpu:latest
    image: tensorlake/blueprints-ultralytics:latest
    command:
      [
        "indexify-cli",
        "executor",
        "--server-addr",
        "indexify:8900"
      ]
    networks:
      server:
    volumes:
      - data:/tmp/indexify-blob-storage
    deploy:
      mode: replicated
      replicas: 1
      # Uncomment this for GPU support
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  data:
