blobStore:
  # allowHTTP: true
  # endpoint: http://blob-store:9000
  credentialSecret: blob-store
  config:
    backend: s3
    s3: {}
    #  accessKey: null
    #  secretKey: null


server:
  image: tensorlake/indexify-server:latest
  labels: {}
  ingress:
    enabled: false
  pod: {}
    # labels: {}
  persistance: {}
    # labels: {}
    # storageClassName: 'local-path'
    # size: 1Gi

executors:
  # Executors is
  - name: indexify-executor
    labels: {}
    image: tensorlake/indexify-executor-default:latest
    replicas: 1

minio:
  enabled: false
