name: Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
      branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: image-builder
    steps:
    - uses: actions/checkout@v3
    - name: Install protoc
      run: sudo apt install -y protobuf-compiler
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        key: test-build-cache
        path: |
          /tmp/pip-*
          ~/.cache/pip
          /usr/lib/python3/dist-packages
          ./target
          ./ui/node_modules
          ./ui/build
          /tmp/.buildx-cache
    - name: test
      run: ./run_tests.sh